version: "3"

services:
    wordpress:
        image: wordpress
        ports:
            - "80:80"
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: wp
            WORDPRESS_DB_PASSWORD: wp_pass
            WORDPRESS_DB_NAME: wp
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wp
            MYSQL_USER: wp
            MYSQL_PASSWORD: wp_pass
    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
